apiVersion: v1
kind: Pod
metadata:
  name: mysql
  label:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5
      env:
        - name: MYSQL_USERNAME
          value: root
        - name: MYSQL_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: mysql
  ports:
    - name: db
      port: 3306
      targetPort: 3306
  type: ClusterIP