apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      mylablename: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      name: webapp
      labels:
        mylablename: webapp
    spec:
      containers:
        - name: webapp
          image: horison/testing-app:lastest
